export const BASE_PATH = '/api/v1'
export const LISTS_PATH = '/lists'
export const ITEMS_PATH = '/lists/:listId/items'
export const ADD_ITEM_PATH = '/lists/:listId/items/add'
export const SORT_ITEMS_PATH = '/lists/:listId/items/sort'
export const DELETE_ITEM_PATH = '/lists/:listId/items/:id/delete'
export const DUPLICATE_ITEM_PATH = '/lists/:listId/items/:id/duplicate'
